#!/bin/bash

# Copyright 2019-2024 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Shengzhou Liu <shengzhou.liu@nxp.com>

# Runtime Dynamic Configuration for single distro image on various NXP i.MX/Layerscape platforms.

set -e

source /usr/bin/board_id.sh
board_id=$(get_board_id)

: ${board_id:?}

case "${board_id}" in
    imx8mm*)
        ln -sf vsidaemon-IMX8MM /usr/bin/vsidaemon
        ln -sf weston.ini.imx8mm /etc/xdg/weston/weston.ini
        /usr/bin/patchelf --replace-needed libGL.so.1 libGLESv2.so.2 /lib/aarch64-linux-gnu/libmutter-16.so.0.0.0

        ;;

    imx8mp*)
        ln -sf /lib/systemd/system/imx8-isp.service /etc/systemd/system/multi-user.target.wants/imx8-isp.service
        ln -sf vsidaemon-IMX8MP /usr/bin/vsidaemon
        /usr/bin/patchelf --replace-needed libGL.so.1 libGLESv2.so.2 /lib/aarch64-linux-gnu/libmutter-16.so.0.0.0
        ;;

    imx91*)
        rm -rf /etc/systemd/system/display-manager.service
        ln -sf weston.ini.imx91 /etc/xdg/weston/weston.ini
        systemctl enable weston || true
        ;;

    imx93*)
        ln -sf libg2d-pxp.so.2.4.0 /usr/lib/libg2d.so.2
        [ -f /usr/lib/libg2d-viv.so.2.4.0 ] && rm -f /usr/lib/libg2d-viv.so.2.4.0
        rm -rf /etc/systemd/system/display-manager.service

        ln -sf weston.ini.imx93 /etc/xdg/weston/weston.ini
        systemctl enable weston || true
        ;;

    imx95*)
        ln -sf weston.ini.imx95 /etc/xdg/weston/weston.ini
        /usr/bin/patchelf --replace-needed libGL.so.1 libGLESv2.so.2 /lib/aarch64-linux-gnu/libmutter-16.so.0.0.0
        ;;

    ls1028a*)
        ln -sf weston.ini.ls1028 /etc/xdg/weston/weston.ini
        rm -rf /etc/systemd/system/display-manager.service
        systemctl enable weston || true
        ;;

    ls1043*|ls1046*)
        ln -sf /lib/systemd/system/fmc.service /etc/systemd/system/multi-user.target.wants/fmc.service
        ;;
esac

sed -i 's/^SUBSYSTEM/#SUBSYSTEM/' /usr/lib/udev/rules.d/50-firmware.rules

/usr/bin/hostnamectl set-hostname "${board_id}"

systemctl disable strongswan.service --now || true

### network config
# disable rename network interface
ln -sf /dev/null /etc/udev/rules.d/80-net-setup-link.rules

# disable legacy networking service
systemctl disable networking --now 2>/dev/null || true

# use systemd-networkd
systemctl enable systemd-networkd --now 2>/dev/null || true

# disable systemd-networkd-wait-online to speed up the boot
systemctl disable systemd-networkd-wait-online --now 2>/dev/null || true
systemctl disable NetworkManager-wait-online --now 2>/dev/null || true

/usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas/ >/dev/null 2>&1

/usr/sbin/ldconfig

/usr/sbin/depmod -a
/usr/sbin/update-initramfs -u 2>/dev/null || true

systemctl disable platcfg.service 2>/dev/null || true

dpkg --configure -a

systemctl daemon-reload
if [[ $PPID -eq 1 ]] && [[ -f /etc/systemd/system/graphical.target.wants/weston.service ]]; then
    systemctl start weston
fi
