#
# Copyright 2017-2023 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
#
# SDK BSP Components

SHELL=/bin/bash
include $(FBDIR)/configs/$(CONFIGLIST)
#include $(FBDIR)/include/repo.mk
#include $(FBDIR)/include/repo_update.inc
include $(FBDIR)/include/utils.mk
include $(FBDIR)/include/download_repo.mk
include $(FBDIR)/include/patch_apply.mk
include $(FBDIR)/configs/.repo_pool
include *.mk

BSPDIR = $(PKGDIR)/bsp
