#!/bin/bash

# Copyright 2021 NXP
#
# SPDX-License-Identifier: BSD-3-Clause


clean_bsp_components() {
	echo "[INFO] Clean the BSP "
    rm -rf $FBOUTDIR/bsp
    rm -rf $PKGDIR/bsp/*
	rm -f $FBDIR/logs/.lsfwdone
	echo "[INFO] Done."
}


clean_linux_components() {
	echo "[INFO] Clean the linux "
    rm -rf $FBOUTDIR/linux
	rm -rf $PKGDIR/linux/*
	echo "[INFO] Done."
}


clean_apps_components() {
	echo "[INFO] Clean the apps "
    rm -rf $DESTDIR
	rm -rf $PKGDIR/apps/*
	echo "[INFO] Done."
}
