#!/bin/bash
#
# Copyright 2017-2021,2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
#
# A generic function to create NOR/QSPI/XSPI/NAND flash or SD/eMMC card composite firmware
# which consists of customizable images separately.
#
# ${BOOT_TYPE} can be sd, emmc, qspi, xspi, nor, nand, defined in configs/board/<machine>.conf
#
# In case of SD/eMMC boot, the DISK_BOOTLOADER_OFFSET is 4k for QorIQ SoC or 1k/32k/33k for i.MX SoC
#
# Shengzhou Liu <shengzhou.liu@nxp.com>
#
# - docs/memory_layout.txt
# - configs/board/common/layerscape_memorylayout.cfg
# - configs/board/<machine>.conf
#
# Can be called independently from the Makefile
#
[ -n "$FBDEBUG" ] && set -xe || set -e
source "${FBDIR}/include/console.sh"

create_composite_firmware() {
    set -e -o pipefail
    if [ "$CONFIG_PLATFORM_LS" = "y" ]; then
        . $FBDIR/configs/board/common/layerscape_memorylayout.cfg
    else
        . $FBDIR/configs/board/common/imx_memorylayout.cfg
    fi

    . $FBDIR/configs/board/${MACHINE}.conf

    if [ -z "${BOOTTYPE}" ] && [ -n "$BOOT_TYPE" ]; then
        BOOTTYPELIST=${BOOT_TYPE}
    elif [ -n "${BOOTTYPE}" ]; then
        BOOTTYPELIST=${BOOTTYPE}
    else
        BOOTTYPELIST=sd
    fi

    [ -z "${DISK_BOOTLOADER_OFFSET}" ] && DISK_BOOTLOADER_OFFSET=4096

    for boottype in ${BOOTTYPELIST}; do
        secopt=""
        [ "${CONFIG_SECURE_BOOT}" = "y" ] && secopt="_sec"

        blname="${boottype}boot${secopt}"
        fw_img=$FBOUTDIR/images/firmware_${MACHINE}_${blname}.img
        rm -f ${fw_img} && img_offset="" && img_file=""

        for i in $(seq 1 "${MAX_COMPOSITE_IMG_NUM}"); do
            img_offset=$(eval echo '$'COMPOSITE_IMG"$i"_OFFSET)
            img_file=""

            if [ "$CONFIG_PLATFORM_LS" = "y" ]; then
                # Skip secure header if secure boot is disabled
                [ "${CONFIG_SECURE_BOOT}" != "y" ] && [ "$i" = "4" ] && continue

                # Build search candidates by priority
                candidates=""
                if [ "${CONFIG_SECURE_BOOT}" = "y" ]; then
                    case $i in
                        1|2|4|5|6)
                        candidates="COMPOSITE_IMG${i}_FILE_${boottype}_sec COMPOSITE_IMG${i}_FILE_sec"
                        ;;
                        *)
                        candidates="COMPOSITE_IMG${i}_FILE"
                        ;;
                    esac
                else
                    # Non-secure mode specific filenames
                    candidates="COMPOSITE_IMG${i}_FILE_${boottype} COMPOSITE_IMG${i}_FILE"
                fi

                # Find the first defined variable in candidates
                for var in $candidates; do
                    img_file=$(eval echo '$'"$var")
                    [ -n "$img_file" ] && break
                done


                # Critical check: if the first image (usually bootloader) is missing, abort this firmware
                [ "$i" = 1 ] && [ -z "${img_file}" ] && rm -f "${fw_img}" && break
            else
                # Default logic for non-LS families
                img_file=$(eval echo '$'COMPOSITE_IMG"$i"_FILE_"$boottype")
            fi

            # Skip ITB image if specified by type
            [ "$i" = "${MAX_COMPOSITE_IMG_NUM}" ] && [ "$COMPOSITE_FW_NO_ITB_TYPE" = "$boottype" ] && break

            # Write image to firmware if file exists
            if [ -n "${img_file}" ] && [ -e "$FBOUTDIR/${img_file}" ]; then
                log_mute echo " Writing ${img_offset} <---> ${FBOUTDIR##*/}/${img_file}"

                target_offset=${img_offset}
                # Adjust offset for SD/eMMC boot media (skipping MBR/partition table area)
                if [ "$i" != 1 ] && { [ "${boottype}" = "sd" ] || [ "${boottype}" = "emmc" ]; }; then
                    target_offset=$((img_offset - DISK_BOOTLOADER_OFFSET))
                fi

                # Convert byte offset to 1K blocks for dd
                seek_val=$((target_offset / 1024))
                dd if="$FBOUTDIR/${img_file}" of="${fw_img}" bs=1K seek=${seek_val} conv=notrunc 2>/dev/null
            fi
        done
        [ -f "${fw_img}" ] && fbprint_d "${fw_img}"; echo
    done

    # Copy SRK hash files for LS family if security tools exist
    if [ "$CONFIG_PLATFORM_LS" = "y" ] && [ "${CONFIG_SECURE_BOOT}" = "y" ]; then
        cp -f "$PKGDIR/apps/security/cst/srk"* "$FBOUTDIR/images/"
    fi
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    create_composite_firmware "$@"
fi
