#!/bin/bash

# Copyright 2017-2021 NXP
#
# SPDX-License-Identifier: BSD-3-Clause



build_distro_rfs_ubuntu() {
    if [ $DISTROTYPE = ubuntu -o $DISTROTYPE = debian ] && [ -f $RFSDIR/etc/buildinfo ]; then
	echo $RFSDIR already exists! && exit 0
    fi
    if [ $DISTROTYPE = ubuntu -o $DISTROTYPE = debian ] && [ ! -f $RFSDIR/etc/buildinfo ]; then
	echo generating $RFSDIR ...
	test -c $RFSDIR/dev/pts/ptmx && sudo umount $RFSDIR/dev/pts
	test -f $RFSDIR/proc/uptime && sudo umount $RFSDIR/proc
	[ -n "$RFSDIR" ] && sudo rm -rf $RFSDIR/*
    fi

    [ -n "$BUILDARG" ] && pkglist=$BUILDARG || pkglist=extra_packages_list
    [ "$RELEASE_TYPE" = external -a $DISTROSCALE = desktop ] && rfsdownloadable=n || rfsdownloadable=y

    if [ "$FETCH_PREBUILT_SDK_RFS" = y -a "$FORCE" != y -a $rfsdownloadable = y ] && \
       [ $DISTROTYPE = ubuntu -o $DISTROTYPE = debian ]; then
       rootfsn=rootfs_${DISTRIB_VERSION}_${DISTROTYPE}_${DISTROSCALE}_${DESTARCH}.tgz
       rootfs_url=$DISTRO_SVR_URL/$DISTRIB_VERSION/$rootfsn
       if [ ! -f $FBOUTDIR/images/$rootfsn ]; then
	   cd $FBOUTDIR/images
	   wget --progress=bar:force $rootfs_url || true
       fi
       [ -f $FBOUTDIR/images/$rootfsn ] && echo Extracting $rootfsn && \
       sudo tar xf $FBOUTDIR/images/$rootfsn -C $RFSDIR || echo Building $RFSDIR from scratch
       cd $FBDIR
    fi

    [ -f $RFSDIR/etc/buildinfo ] || . $FBDIR/tools/create_distrorfs $SYSARCH $CODENAME $DISTROSCALE $pkglist

    if [ -d $RFSDIR/etc/udev/rules.d ]; then
	sudo cp -f $FBDIR/src/misc/udev/udev-rules-qoriq/72-fsl-dpaa-persistent-networking.rules $RFSDIR/etc/udev/rules.d
	sudo cp -f $FBDIR/src/misc/udev/udev-rules-qoriq/73-fsl-enetc-networking.rules $RFSDIR/etc/udev/rules.d
	sudo cp -f $FBDIR/src/misc/udev/udev-rules-imx/10-imx.rules $RFSDIR/etc/udev/rules.d
    fi
    fbprint_d $RFSDIR
}
