#!/bin/bash

# Copyright 2017-2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause


build_distro_rfs_debian() {
    [ $DISTROTYPE = debian ] && [ -f $RFSDIR/etc/buildinfo ] && \
    log_mute echo "$RFSDIR already exists!" && exit 0
	rfs_umount

    [ `whoami` = root ] && sudopt="" || sudopt=sudo

    fbprint_n "Generating initial rootfs: $RFSDIR"
    cd $FBDIR
    test -c $RFSDIR/dev/pts/ptmx && $sudopt umount $RFSDIR/dev/pts
    test -f $RFSDIR/proc/uptime && $sudopt umount $RFSDIR/proc
    [ -n "$RFSDIR" ] && $sudopt rm -rf $RFSDIR/*

    if [ "$FETCH_PREBUILT_SDK_RFS" = y -a "$FORCE" != y ]; then
        echo FETCH_PREBUILT_SDK_RFS is enable by default in $CFGLISTYML
        rootfsn=rootfs_${DISTRIB_VERSION}_${DISTROTYPE}_${DISTROVARIANT}_${DESTARCH}.tar.zst
        rootfs_url=$DISTRO_SVR_URL/$DISTRIB_VERSION/$rootfsn
        if [ ! -f $FBOUTDIR/images/$rootfsn ]; then
           cd $FBOUTDIR/images
           log_mute wget --progress=bar:force $rootfs_url || true
           cd -
	    fi
	    [ -f $FBOUTDIR/images/$rootfsn ] && echo Extracting $rootfsn && \
	        $sudopt tar -I zstd -xf $FBOUTDIR/images/$rootfsn -C $RFSDIR && \
	        fbprint_d $RFSDIR && exit || echo Building $RFSDIR from scratch
    fi

    if [ -n "$DISTROVARIANT" -a "$DISTROVARIANT" = "base" ]; then
        PKGS=''
        NEWRFSDIR=$FBOUTDIR/rfs/rootfs_${DISTRIB_VERSION}_debian_base_arm64
        RFSCMD=$FBDIR/configs/debian/debian_base_arm64.sh
    else
		case "$MACHINE" in
			   imx8*|imx95*)    PKGS="$ls_pkgs $imx9_pkgs $imx8_pkgs"; log_mute echo imx8 package...  ;;
			   imx9*)           PKGS="$ls_pkgs $imx9_pkgs" ; log_mute echo imx9 package... ;;
			   l*)  	        PKGS="$ls_pkgs" ; log_mute echo ls  package... ;;
			   *)               PKGS="$ls_pkgs $imx9_pkgs" ; log_mute echo imx9 package... ;;
		esac
        NEWRFSDIR=$RFSDIR
        RFSCMD=$FBDIR/configs/debian/debian_server_arm64.sh
    fi
    [ -f $NEWRFSDIR/etc/buildinfo ] && log_mute echo "$NEWRFSDIR already exists!" && exit 0

    rm -rf $NEWRFSDIR && mkdir -p $NEWRFSDIR
    $sudopt bash $RFSCMD $NEWRFSDIR $PKGS
	echo -e "Debian GNU/Linux 13" | $sudopt tee -a $NEWRFSDIR/etc/buildinfo 1>/dev/null

    case "$MACHINE" in
    ls1028*)
        mkdir -p $NEWRFSDIR/etc/xdg/weston
        cp -f $FBDIR/src/system/weston/weston.ini.ls1028 $NEWRFSDIR/etc/xdg/weston/
        ;;
    imx*)
        mkdir -p $NEWRFSDIR/etc/xdg/weston
        cp -f $FBDIR/src/system/weston/weston.ini* $NEWRFSDIR/etc/xdg/weston/
        # for gnome desktop
        if [ -f $NEWRFSDIR/etc/pam.d/gdm-password ]; then
            cp -f $FBDIR/src/system/gdm/daemon.conf $NEWRFSDIR/etc/gdm3
            cp -f $FBDIR/src/system/gdm/gdm-password $NEWRFSDIR/etc/pam.d
            cp -f $FBDIR/src/system/gdm/gdm.service $NEWRFSDIR/lib/systemd/system/
            ln -sf /lib/systemd/system/gdm.service $NEWRFSDIR/etc/systemd/system/graphical.target.wants/gdm.service
        fi
        ;;
    esac


    # fix absolute path for libz.so symlink when cross compiling apitrace
    $sudopt ln -sf libz.so.1 $NEWRFSDIR/usr/lib/aarch64-linux-gnu/libz.so

    # fixup for libtinfo.so needed by tsntool
    $sudopt ln -sf libtinfo.so.6 $NEWRFSDIR/usr/lib/aarch64-linux-gnu/libtinfo.so

    # fixup for Qt6 app cross-compiling
    $sudopt ln -sf libQt6Quick.so.6 $NEWRFSDIR/usr/lib/aarch64-linux-gnu/libQt6Quick.so
    $sudopt ln -sf libQt6OpenGL.so.6 $NEWRFSDIR/usr/lib/aarch64-linux-gnu/libQt6OpenGL.so
    $sudopt ln -sf libQt6QmlModels.so.6 $NEWRFSDIR/usr/lib/aarch64-linux-gnu/libQt6QmlModels.so
    $sudopt ln -sf libQt6Qml.so.6 $NEWRFSDIR/usr/lib/aarch64-linux-gnu/libQt6Qml.so

    #echo -e 'export PYTHONPATH=$PYTHONPATH:/usr/lib/python3.13/dist-packages:/usr/lib/python3/dist-packages' | $sudopt tee -a $NEWRFSDIR/etc/profile 1>/dev/null

    # fix ping: socket: Operation not permitted
    $sudopt chmod u+s $NEWRFSDIR/bin/ping

    fbprint_d $NEWRFSDIR
}
