#!/bin/bash

# Copyright 2017-2021 NXP
#
# SPDX-License-Identifier: BSD-3-Clause



build_distro_rfs_centos() {
    [ $DESTARCH != arm64 ] && echo The supported CentOS arch: arm64 && exit 1
    [ -f $RFSDIR/etc/buildinfo ] && echo $RFSDIR already exists! && exit 0
    if [ -d $RFSDIR -a ! -f $RFSDIR/etc/buildinfo ]; then
	[ -n "$RFSDIR" ] && sudo rm -rf $RFSDIR/*
    fi
    echo "building $RFSDIR ..."
    centos_url=`eval echo '${'"centos_""$DESTARCH"'_url}'`
    if [ ! -s $FBOUTDIR/rfs/centos_${DESTARCH}_squashfs.img ]; then
	wget --progress=bar:force $centos_url -O $FBOUTDIR/rfs/centos_${DESTARCH}_squashfs.img
	[ $? != 0 -o ! -s $FBOUTDIR/rfs/centos_${DESTARCH}_squashfs.img ] && \
	fbprint_e "Failed to download $centos_url" && exit
    fi
    echo Extracting CentOS squashfs.img ...
    mkdir -p $FBOUTDIR/rfs/{centosmnt,centosmnt2}
    sudo mount -o loop $FBOUTDIR/rfs/centos_${DESTARCH}_squashfs.img $FBOUTDIR/rfs/centosmnt && \
    sudo mount -o loop $FBOUTDIR/rfs/centosmnt/LiveOS/rootfs.img $FBOUTDIR/rfs/centosmnt2 && \
    sudo cp -Prf --preserve=mode,timestamps $FBOUTDIR/rfs/centosmnt2/* $RFSDIR/ && \
    sudo umount $FBOUTDIR/rfs/centosmnt2 && sudo umount $FBOUTDIR/rfs/centosmnt
    if [ $? = 0 ]; then
	distrots=${DISTROTYPE}_${centos_version}_${DESTARCH}_`date +%Y%m%d%H%M`
	echo $distrots | sudo tee $RFSDIR/etc/buildinfo
	rm -rf $FBOUTDIR/rfs/{centosmnt,centosmnt2}
    else
	echo Failded to build $RFSDIR && exit 1
    fi

    if [ -d $RFSDIR/etc/udev/rules.d ]; then
	sudo cp -f $FBDIR/src/misc/udev/udev-rules-qoriq/72-fsl-dpaa-persistent-networking.rules $RFSDIR/etc/udev/rules.d
    fi
    sudo cp -f $FBDIR/src/misc/boot.mount $RFSDIR/etc/systemd/system/
    sudo rm -f $RFSDIR/etc/systemd/system/default.target
    sudo ln -sf $RFSDIR/usr/lib/systemd/system/multi-uset.target $RFSDIR/etc/systemd/system/default.target
    sudo rm -rf $RFSDIR/lib/modules && sudo rm -rf $RFSDIR/boot/*
    sudo ln -sf /boot/modules $RFSDIR/lib/modules
    if [ $DESTARCH = arm64 ]; then
	# reinstall yum
	cd $RFSDIR && yum_url=`eval echo '${'"yum_""$DESTARCH"'_url}'`
	wget --progress=bar:force $yum_url -O $RFSDIR/yum.rpm
	sudo rpm2cpio $RFSDIR/yum.rpm | sudo cpio -divu && rm -f $RFSDIR/yum.rpm
    fi
    sudo mkdir -p $RFSDIR/etc/yum.repos.d
    sudo cp -f $FBDIR/configs/centos/CentOS-Base.repo $RFSDIR/etc/yum.repos.d
    sudo ln -sf ../boot.mount $RFSDIR/etc/systemd/system/local-fs.target.wants/boot.mount
    fbprint_d $RFSDIR
}
