#!/bin/bash
#
# Copyright 2017-2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
#
# A general distro installer
#
# Author: Shengzhou Liu <shengzhou.liu@nxp.com>
#

set -e

FIVERSION=lsdk2606
DEFAULT_PARTITION_NUMBER=3
DEFAULT_BOOT_PARTITION_NUM=1
DEFAULT_ROOT_PARTITION_NUM=2
DEFAULT_DISK_PARTITION="2P=512M:-1"
DEFAULT_LOOP_DEVICE_PARTITION="2P=512M:-1"
DEFAULT_SDCARD_IMG_SIZE_MB=10240
DEFAULT_RAW_PARTITION_SIZE_MB=256
DEFAULT_DISTRO_SVR_URL=https://www.nxp.com/lgfiles/sdk/$FIVERSION
MAX_PRIMARY_PARTITIONS=4  # Maximum number of primary partitions in MBR partition table
# Cleanup function for signal handling
cleanup_on_exit() {
    local exit_code=$?
    [ $exit_code -ne 0 ] && print_w "\nCleaning up resources"
    if [ -n "$devpartname" ]; then
        # Unmount all partitions
        mntlist=$(cat /proc/mounts 2>/dev/null | grep /dev/${devpartname} | cut -d' ' -f1 | tr '\n' ' ' || true)

        for mntp in $mntlist; do
            sudo fuser -k $mntp &>/dev/null || true
			sleep 1
            sudo umount $mntp &>/dev/null || true
            # print_w "Unmounted $mntp"
        done

        # Clean up loop device if used
        if [[ "$devname" =~ ^loop[0-9]+$ ]] && [ -n "$devname" ]; then
            if sudo losetup -l | grep -q "/dev/$devname"; then
                sudo losetup -d /dev/$devname &>/dev/null || true
                # print_w "Detached loop device /dev/$devname"
            fi
        fi
    fi

    # Clean up temporary directory if exists
    if [ -n "$temp_dir" ] && [ -d "$temp_dir" ]; then
        rm -rf "$temp_dir" &>/dev/null || true
    fi

    # Remove mount point directories and mntdir itself
    if [ -n "$mntdir" ] && [ -d "$mntdir" ]; then
        for mntpoint in $mntdir/*; do
            if [ -d "$mntpoint" ]; then
                sudo umount "$mntpoint" &>/dev/null || true
                sudo rmdir "$mntpoint" &>/dev/null || true
                # print_w "Removed mount point $mntpoint"
            fi
        done
        # Remove the main mntdir
        rm -rf "$mntdir" &>/dev/null || true
        # print_w "Removed temporary mount directory $mntdir"
    fi

    if [ $exit_code -ne 0 ]; then
        print_e "\nOperation interrupted or failed. Cleanup completed."
    fi

    exit $exit_code
}

# Set up signal traps
trap cleanup_on_exit EXIT
trap 'exit 130' INT  # Ctrl+C (SIGINT)
trap 'exit 143' TERM # SIGTERM

usage ()
{
cat <<EOF
Usage:  flex-installer [ -i <instruction> ] [ -b <boot> ] [ -r <rootfs> ] [ -f <firmware> ] [ -d <device> ] [ -m <machine> ]
OPTION:
 -i, --instruction  Instruction to execute, valid argument as below:
     'auto[:distrover]'	      Automatically download and install [specified] distro images to storage device
     'pf'                     Partition and format storage device
     'install'                Install distro images to storage device without downloading
     'list'                   List the supported machines and environments for installation
     'download[:distrover]'   Only download [specified] distro images without installation
     'mkwic'        Create all-in-one sdcard WIC image including composite bsp firmware, boot image and rootfs
 -b, --bootimg	    The boot partition image
 -r, --rootfsimg    The root partition image
 -B, --bootpart     Specify boot partition number to override default (default boot partition is the first)
 -R, --rootpart     Specify root partition number to override default (default root partition is the last)
 -d, --device	    Device name of the target SD/USB/SATA storage drive in Linux
 -p, --partition    Customize configurable partitions of target disk, default is "-p 3P=512M:8G:-1" if not specified
 -f, --firmware	    The composite firmware image to be programmed into SD card
 -F, --force        Force partition and format target disk regardless of the existing data in disk
 -m, --machine	    Target machine name to specify the name of composite firmware for automatical deployment
 -u, --url	        Specify URL of distro webserver to override the default one for automatically downloading distro
 -o, --offset       Specify the offset to burn firmware to SD card (e.g. 1k, 4k, 32k, 33k)
 -v, --version	    Print version info

Examples for various usage scenarios:
- Automatically download and install distro images onto target storage drive on host machine or ARM board:
  $ flex-installer -i pf -d /dev/mmcblk0                                (partition and format SD/eMMC card)
  $ flex-installer -i auto -m imx8mpevk -d /dev/mmcblk0 [ -r <rootfs> ] (automatically download and install Debian distro)
  You can specify one or several of '-b <boot> -r <rootfs> -f <firmware> -u <url>' options to override the default settings

- To only partition and format target SD/eMMC card or USB/SATA disk
  $ flex-installer -i pf -d /dev/sdx                   (default 2 partitions as 2P=512M:-1)
  or
  $ flex-installer -i pf -d /dev/sdx -p 4P=800M:6G:8G:-1 (specify custom partitions as 4P=800M:6G:8G:-1)

- To install local image to SD card
  $ flex-installer -d /dev/sdx -m <machine> -f firmware_<machine>_sdboot.img -b boot_IMX_arm64.tar.zst -r rootfs_lsdk_debian_arm64.tar.zst
  or
  $ flex-installer -r rootfs_lsdk_debian_xx_arm64.tar.zst -d /dev/sdx         (only install rootfs partition image)
  $ flex-installer -b boot_IMX_arm64_lts_xx.tar.zst -d /dev/sdx -m <machine>  (only install boot partition image)
  $ flex-installer -f firmware_<machine>_sdboot.img -d /dev/sdx -m <machine>  (only install composite firmware image)

- Install rootfs image into the 2nd partition instead of the default 3rd partition:
  $ flex-installer -r <rootfs> -R 2 -d /dev/mmcblk0
  After installing successfully, run "setenv devpart_root 2;boot" in U-Boot to boot distro from the 2nd partition

- Create the all-in-one sdcard WIC image
  $ flex-installer -i mkwic -m <machine> -f <firmware> -b <boot> -r <rootfs>

- Backup rootfs and bootpartition from target storage device
  $ flex-installer -i backup -d /dev/sdX
EOF
    exit
}

ls_machine_list=' ls1028ardb ls1043ardb ls1046ardb lx2160ardb la1224rdb '
imx_machine_list=' imx8mmevk imx8mpevk imx8mpfrdm imx8qmmek imx91evk imx91frdm imx91sfrdm imx93evk imx93frdm imx95-15x15-frdm imx95-15x15-evk imx95-19x19-frdm-pro imx95-19x19-evk '

get_linux_version() {
    local distro_ver=$1
    local linux_version

    case "$distro_ver" in
        lsdk2606) linux_version="6.12.49" ;;
        lsdk2512) linux_version="6.12.20" ;;
        lsdk2506) linux_version="6.6.52" ;;
        lsdk2412) linux_version="6.6.36" ;;
        lsdk2406) linux_version="6.6.3" ;;
        *) print_w "Unknown distro version: $distro_ver"; exit 1;;
    esac

    echo "$linux_version"
}

calculate_partition_total_size() {
    # Calculate total size of partitions in MB
    # $1: partition configuration string (e.g., "2P=512M:-1")
    local partition_config=$1
    local total_mb=$((DEFAULT_RAW_PARTITION_SIZE_MB + 4))
    local part_num=$(echo $partition_config | cut -d= -f1 | sed 's/P//')

    for ((i=1; i<=$part_num; i++)); do
        eval local n_p$i=`echo $partition_config | cut -d: -f$i`
        [ $i = 1 ] && n_p1=`echo $n_p1 | cut -d= -f2`
        local n_p=`eval echo '${n_p'"$i"'}'`

        # Skip -1 (use remaining space)
        [ "${n_p: -2}" = "-1" ] && continue

        # Convert to MB
        if [ ${n_p: -1} = G ]; then
            local size_mb=$((${n_p%?} * 1024))
        elif [ ${n_p: -1} = M ]; then
            local size_mb=${n_p%?}
        else
            print_e "Invalid partition size format: $n_p"
            return 1
        fi

        total_mb=$((total_mb + size_mb))
    done

    echo $total_mb
}


search_dev() {
    devlist=`ls /dev/sd?`
    for dev in $devlist; do
	sdx=`udevadm info -q all -n $dev | grep ID_BUS`
	disksize=$[ `sudo fdisk -ls $dev` / 1000000 ]
	if [ $1 = usb ] ; then
	    if [ ${sdx:10:3} = usb ]; then
		devusb=${dev:5:3}
		echo "USB disk: $devusb $disksize GB"
		break
	    fi
	elif [ $1 = sata ]; then
	    if [ ${sdx:10:3} = ata ]; then
		devsata=${dev:5:3}
		echo "SATA disk: $devsata $disksize GB"
		break
	    fi
	fi
    done
}


get_device_name_in_tinydistro() {
    # for automation test with '-d sd|usb|sata' instead of '-d /dev/sdx' in tiny distro by searching 1st available device on remote board
    if [ "$mediadevice" = "sd" ]; then
	[ ! -b /dev/mmcblk0 ] && echo "SD/MMC device is not available" && exit || devname=mmcblk0
    elif [ "$mediadevice" = "usb" ] ; then
	search_dev usb
	devname=$devusb
	[ -z "$devname" ] && echo "USB device is not available" && exit
    elif [ "$mediadevice" = "sata" ] ; then
	search_dev sata
	devname=$devsata
	[ -z "$devname" ] && echo "SATA device is not available" && exit
    elif echo "$mediadevice" | grep -q /; then
	devname=${mediadevice##*/}
    fi

    [ ${devname:0:6} = mmcblk -o ${devname:0:4} = loop ] && devpartname=${devname}p || devpartname=$devname
}


get_device_name_on_host() {
    devname=${mediadevice##*/}
    [ ${devname:0:6} = mmcblk -o ${devname:0:4} = loop ] && devpartname=${devname}p || devpartname=$devname
}


umount_device() {
    mntlist=$(cat /proc/mounts | grep /dev/${devpartname} | cut -d' ' -f1 | tr '\n' ' ')

    for mntp in $mntlist; do
	if [ $intinyrfs = y -a `pwd` = "$rootpartition" ]; then
	    continue
	else
	    sudo fuser -k $mntp &>/dev/null || true
	    sudo umount $mntp || true
	fi
    done
}


mount_device() {
    [ $pnum -ge 5 ] && max=$[ $pnum + 1 ] || max=$pnum
    for i in $(seq 1 $max); do
	[ $pnum -ge 5 -a $i = 4 ] && continue
	sudo mkdir -p $mntdir/${devpartname}$i
	if ! mount | grep -q ${devpartname}$i; then
	    sudo mount /dev/${devpartname}$i $mntdir/${devpartname}$i 1>/dev/null 2>&1 || true
	fi
    done
}


program_firmware_to_sd() {
    # $1: firmware file,  $2: block device
    [ ! -b $2 ] && echo device $device not found && exit
    [ ! -r $1 ] && echo firmware $1 not found && exit

    if [ -n "$disk_offset" ]; then
	offset=${disk_offset::-1}
    elif echo $machine | grep -qE 'imx6|imx7'; then
	offset=1
    elif echo $machine | grep -qE 'imx8mq|imx8mm'; then
        offset=33
    elif echo $machine | grep -qE 'imx8|imx9'; then
	offset=32
    else
	# for Layerscape platforms
	offset=4
    fi

    sudo dd if=$1 of=$2 bs=1k seek=$offset && sync
    print_d "Program $1 to $2 with offset ${offset}K"
}


check_partition_number() {
    [ -z "$diskpartition" ] && print_e "Please specify partition settings" && exit

    if ! [[ $diskpartition =~ ^[2-9]+[P=]+[0-9]+[G,M]* ]] || \
	echo $diskpartition | tr -d '[0-9] [:,-]' | grep  -E '[^P,M,G]'; then
	print_e "The number of partitions should be >= 2 and the unit of size is G or M"
	print_w "Example: '-p 5P=100M:2G:5G:6G:-1', '-1' indicates the rest space of target disk for the last partition as rootfs"
	[ "$force_opt" != y ] && exit
    fi
    pnum=`echo $diskpartition | cut -d= -f1`
    pnum=${pnum%?}
    partlistnum=$(echo $diskpartition | awk -F":" '{print NF-1}')
    partlistnum=$[ $partlistnum + 1 ]
    [ $pnum != $partlistnum ] && print_e "ERROR: You set $pnum partitions, but listed $partlistnum partitions" && exit || true
    [ $pnum -ge 5 ] && totalparts=$[ $pnum + 1 ] || totalparts=$pnum
}

check_device_partitions() {
    [ -b /dev/$devname ] || { print_w "/dev/$devname not found"; exit; }
    [ -z "$pnum" ] && pnum=$DEFAULT_PARTITION_NUMBER
    [ -z "$totalparts" ] && totalparts=$DEFAULT_PARTITION_NUMBER
    [ -n "$diskpartlist" ] && check_partition_number && partition_format_disk $diskpartition && return

    if sudo parted -s /dev/$devname print 2>/dev/null | grep -qE 'unrecognised disk|Partition Table: unknown'; then
	partition_format_disk $diskpartition && return
    fi

    actual_pnum=$(sudo parted -s /dev/$devname print | grep -E "^ [0-9]" | wc -l)
    [ $actual_pnum -le 1 ] && partition_format_disk $diskpartition && return

    [ $instruction != pf ] && pnum=$actual_pnum
    if sudo parted -s /dev/$devname print | grep -q extended; then
	pnum=$[ $pnum -1 ]
    fi

    mount_device
}
partition_format_disk() {
    if [ -n "$rootdev" ] && mount | grep -q "$rootdev on / type"; then
	print_w "The target /dev/$devname can't be the running device in which $rootdev is running as rootfs"
	print_w "You can choose a non-running device or do the installation in TinyLinux environment" && exit
    fi
    print_n "Partitioning /dev/$devname"

    [ -z "$force_opt" -a ${devname:0:4} != loop -a $instruction != pf -a $instruction != mkwic ] && [ $actual_pnum -ge 3 ] && check_distro_in_disk

    optimal_io_size=$(sudo cat /sys/block/$devname/queue/optimal_io_size)
    minimum_io_size=$(sudo cat /sys/block/$devname/queue/minimum_io_size)
    [ "$optimal_io_size" = "0" ] && aligntype=minimal || aligntype=optimal
    [ $pnum -le 1 ] && parttable=gpt || parttable=msdos

    umount_device
    sudo rm -rf $mntdir/${devpartname}*/*

    sudo parted -a $aligntype -s /dev/$devname mklabel $parttable

    for ((i=1; i<=$pnum; i++)); do
	eval n_p$i=`echo $1 | cut -d: -f$i`
	[ $i = 1 ] && n_p1=`echo $n_p1 | cut -d= -f2`
	n_p=`eval echo '${n_p'"$i"'}'`
	[ ${n_p: -1} = G ] && n_p=${n_p%?} && n_p=$[ $n_p * 1024 ]
	[ ${n_p: -1} = M ] && n_p=${n_p%?}
	[ ${n_p: -2} = -1 ] && eval e_p$i=100%
	[ $i = 1 ] && s_p1=$[ $DEFAULT_RAW_PARTITION_SIZE_MB + 4 ] && e_p1=$[ $s_p1 + $n_p ] && umount_device && \
	sudo parted -a $aligntype -s /dev/$devname mkpart primary ${s_p1}MiB ${e_p1}MiB && continue

	n=$[ i-1 ] && a_e_p=`eval echo '${e_p'"$n"'}'`
	eval s_p$i=$[ $a_e_p + 1 ] && s_p=`eval echo '${s_p'"$i"'}'`
	[ ${n_p: -2} = -1 ] && eval e_p$i=100% || eval e_p$i=$[ $s_p + $n_p ]
	e_p=`eval echo '${e_p'"$i"'}'`

	# use logical partition in case more than 4 partitions for Layerscape SoC
	# as only 4KB space available as partition table of SD card for Layerscape SoC, 32KB for i.MX SoC
	if [ $pnum -le $MAX_PRIMARY_PARTITIONS ]; then
	    parttype=primary
	elif [ $i -le $(($MAX_PRIMARY_PARTITIONS - 1)) ]; then
	    parttype=primary
	elif [ $i -eq $MAX_PRIMARY_PARTITIONS ]; then
	    parttype=extended
	    end=100%
	    umount_device
	    sudo parted -a $aligntype -s /dev/$devname mkpart $parttype ${s_p}MiB $end
	    s_p=$[ $s_p + 1 ]
	    parttype=logical
	    extendedpart=$MAX_PRIMARY_PARTITIONS
	else
	    parttype=logical
	fi
	[ $e_p != 100% ] && end=${e_p}MiB || end=${e_p}
	umount_device
	sudo parted -a $aligntype -s /dev/$devname mkpart $parttype ${s_p}MiB $end
    done

    print_n "Formatting partitions"
    [ -f /usr/bin/man -a  ${devname:0:4} != loop  ] && man ext4 | grep -q metadata_csum && metadataopt=",^metadata_csum"
    for ((i=1; i<=$totalparts; i++)); do
		if [ $i = "$bootpartnum" ]; then
			sudo mkfs.ext4 -F -q -b 4096 -L boot -O ^64bit$metadataopt $bootdev || true
		else
			if [ $i = "$rootpartnum" ]; then
				label=system
			elif [ $i = "$backuppartnum" ]; then
				label=backup
			else
				label=data$i
			fi
			[ $i != "$extendedpart" ] && sudo mkfs.ext4 -F -q -O ^huge_file,^64bit$metadataopt -b 4096 -L $label /dev/${devpartname}$i || true
		fi
    done

    mount_device
    sudo parted -s /dev/$devname print
    print_d "partition and format /dev/$devname"
}


flex_install_distro() {
    # install composite firmware
    if [ -n "$firmware" -o $instruction = auto ] && [ -f $firmware_n ]; then
	umount_device
	program_firmware_to_sd $firmware_n /dev/$devname
    fi
    mount_device

    # install boot partition
    if [ -n "$bootimg" -o $instruction = auto -o $instruction = mkwic ] && [ -d $bootimg_n -o -f $bootimg_n ]; then
        [ -f $bootpartition/buildinfo ] && echo Cleaning the existing data in $bootdev && \
        sudo rm -rf $bootpartition/*
        echo Installing $bootimg_n to $bootdev
        [ $bootimgtype = dir ] && sudo cp -rfp $bootimg_n/* $bootpartition
        [ $bootimgtype = tgz ] && sudo tar xfm $bootimg_n -C $bootpartition
        [ $bootimgtype = zst ] && zstd -d -f $bootimg_n && sudo tar xfm ${bootimg_n%.*} -C $bootpartition

        prefix_to_keep=""
        case "$machine" in
            imx8*)
                prefix_to_keep="${machine:0:6}" ;;
            imx9*)
                prefix_to_keep="${machine:0:5}" ;;
            lx*|ls*|la*)
                prefix_to_keep="fsl-${machine:0:6}" ;;
            *)
                echo "Unsupported machine type: $machine"
                exit 1 ;;
        esac
        sudo find "$bootpartition" -maxdepth 1 -type f -name "*.dtb" ! -name "${prefix_to_keep}*.dtb" -delete 2>/dev/null || true
        #sudo find "$bootpartition" -maxdepth 1 -type f -name "*.scr" ! -name "${machine}_boot.scr" -delete 2>/dev/null || true

        #[ -n "$machine" ] && sudo ln -sf ${machine}_boot.scr $bootpartition/boot.scr
        print_d "Install $bootimg_n in $bootdev"
    fi

    # install system rootfs
    if [ -n "$rootfsimg" -o $instruction = auto -o $instruction = mkwic ] && [ -d $rootfsimg_n -o -f $rootfsimg_n ]; then
	check_running_rfs $rootdev
	[ -d $rootpartition/var/lib ] && [ $instruction != mkwic ] && check_directory $rootpartition
	echo Installing $rootfsimg_n to $rootdev
	if mount | grep -q "$rootdev on / type"; then
	    print_w "Can't install rootfs image to the running root filesystem" && exit
	fi
	case $rfsimgtype in
	    dir)  sudo cp -rfp $rootfsimg_n/* $rootpartition;;
	    tgz)  sudo tar xfm $rootfsimg_n -C $rootpartition;;
	    zst)  zstd -d -f $rootfsimg_n && sudo tar xfm ${rootfsimg_n%.*} -C $rootpartition;;
	ext|wic)  sudo dd if=$rootfsimg_n of=$rootdev bs=4M && sync;;
	cpio.gz)  mv $rootfsimg_n $rootpartition && cd $rootpartition && \
		  gunzip $rootfsimg_n && cpio -idm < ${rootfsimg_n::-3} && cd -;;
	    *)    echo format $rfsimgtype is not supported; exit
	esac
	print_d "Install $rootfsimg_n in $rootdev"
    fi


    if [ $instruction = auto -o $instruction = install -o $instruction = mkwic ]; then
	if [ $bootpartnum != 0 ]; then
	    uuid_boot=$(sudo blkid -s UUID -o value $bootdev)
	    [ -z "$uuid_boot" ] && print_e "Failed to get PARTUUID on $bootdev, please partition and format /dev/$devname" && exit
	    bootmountfile=$rootpartition/lib/systemd/system/boot.mount
	    if [ -f $bootmountfile ] && grep -q '^What=UUID=' $bootmountfile; then
                echo setting UUID $uuid_boot for boot partition $bootdev
		mkdir -p $rootpartition/boot
		sudo chmod 666 $bootmountfile
                sudo sed -i s/What=UUID=.*/What=UUID=$uuid_boot/ $bootmountfile
		sudo chmod 644 $bootmountfile
            fi
	fi

	fstabfile=$rootpartition/etc/fstab
	if [ -f $fstabfile  ] && ! grep -q '^/dev/root' $fstabfile; then
	    sudo chmod 666 $fstabfile
	    sudo echo "/dev/root     /    ext4       errors=remount-ro 0  1" >> $fstabfile
	    sudo chmod 644 $fstabfile
	fi

	if [ -f $rootpartition/etc/apt/apt.conf ] && grep -iq 'acquire::http::proxy' $rootpartition/etc/apt/apt.conf; then
	    sudo sed -i  '/::proxy/d' $rootpartition/etc/apt/apt.conf
	fi
    fi

    echo syncing data
    sync
    umount_device

    if [ $instruction = auto -o -n "$bootimg" -o -n "$rootfsimg" ]; then
	if [ -f $bootmountfile ] && ! grep -q $uuid_boot $bootmountfile; then
	    print_e "Installation failed"
	else
	    print_n "Installation completed successfully"
	fi
    fi

    if [ $rootpartnum != $DEFAULT_ROOT_PARTITION_NUM ] && [ `uname -m` = aarch64 ] && [ $instruction != mkwic ]; then
	print_w "NOTICE: as you configured non-default boot partitions, please reboot the board and under U-Boot run:"
	print_w "'setenv devpart_root $rootpartnum; boot' to boot distro from the custom partition"
    fi
}

check_directory() {
    if [ -z "$force_opt" -a ${devname:0:4} != loop ] && [ "`ls -A $1`" != "" -a "`ls -A $1`" != "lost+found" ]; then
	print_w "\nNOTICE: Appears $1 contains the existing data"
	read -t 180 -n 1 -p "Are you sure to drop the data in $1 partition to proceed now? [y/n] " rdresult && echo ""
	[ -z "$rdresult" ] && rdresult=n
	[ "$rdresult" != y -a "$rdresult" != n ] && echo $rdresult is invalid, valid: y or n && exit
	if [ $rdresult = n ]; then
	    print_w "\nPlease backup important data in $1 if needed, or force the installation with '-F' option" && exit
	else
	    echo Cleaning data in $1 && sudo rm -rf $1/*
	fi
    fi
}


check_running_rfs() {
    if mount | grep -q "$1 on / type ext4"; then
	print_w "Warnning: Can't install rootfs to the running root filesystem"
	print_w "Please select a non-running partition for the installation" && exit
    fi
}


check_distro_in_disk() {
    if [ -b $backupdev ] && ! mount | grep -q $backuppartition; then
	sudo mount $backupdev $backuppartition || true
    fi
    if [ -b $rootdev ] && ! mount | grep -q $rootpartition; then
	sudo mount $rootdev $rootpartition || true
    fi
    for tdir in $backuppartition $rootpartition; do
	if [ -d $tdir/var/lib ]; then
	    check_directory $tdir
	fi
    done
}


check_images_format() {
    if [ -d $bootimg_n ]; then
	bootimgtype=dir
    elif echo $bootimg_n | grep -q .tar.zst && file -L $bootimg_n | grep -q 'Zstandard compressed'; then
	bootimgtype=zst
    elif file -L $bootimg_n | grep -q 'gzip compressed'; then
	bootimgtype=tgz
    elif file -L $bootimg_n | grep -q 'UUID='; then
	bootimgtype=ext
    elif [ $instruction != auto ] && [ -n "$bootimg" ] && [ ! -e $bootimg ]; then
	print_e "Not found $bootimg"; exit 1
    else
	bootimgtype=unknown
    fi

    if [ -d $rootfsimg_n ]; then
	rfsimgtype=dir
    elif echo $rootfsimg_n | grep -q .tar.zst && file -L $rootfsimg_n | grep -q 'Zstandard compressed'; then
	rfsimgtype=zst
    elif echo $rootfsimg_n | grep -q .cpio.gz && file -L $rootfsimg_n | grep -q 'gzip compressed'; then
	rfsimgtype=cpio.gz
    elif file -L $rootfsimg_n | grep -q 'gzip compressed'; then
	rfsimgtype=tgz
    elif file -L $rootfsimg_n | grep -q 'UUID='; then
	rfsimgtype=ext
    elif [ $instruction != auto ] && [ -n "$rootfsimg" ] && [ ! -e $rootfsimg ]; then
	print_e "Not found $rootfsimg"; exit 1
    else
	rfsimgtype=unknown
    fi
}


check_network_access() {
    if echo $url | grep -q //; then
	remoteserver=$(echo $url | cut -d/ -f3)
    else
	remoteserver=$(echo $url | cut -d/ -f1)
    fi
    retcode=$(curl -I -m 10 -o /dev/null -s -w %{http_code} $remoteserver) || true

    if [ ${retcode:0:1} != 2 -a ${retcode:0:1} != 3 ]; then
	print_e "ERROR: HTTP returned $retcode, unable to access $remoteserver to fetch distro image"
	print_e "Please check your network to ensure $remoteserver is accessable via HTTP from this machine"
	print_e "Please check HTTP proxy settings if needed in your environment"
	exit
    fi
}


check_http_request() {
    retcode=$(curl -I -m 10 -o /dev/null -s -w %{http_code} $1) || true
    if [ "$retcode" != 200 -a "$retcode" != 000 ]; then
	print_e "The requested URL $1 returned error $retcode"
	exit
    fi
}


download_distro() {
	temp_dir=$(mktemp -d)

	check_http_request $bootimg_url

	if [ -f ${firmware_url##*/} ]; then
		echo -e "${firmware_url##*/} already exists"
	else
		echo -e "\n Downloading $firmware_url "
		if curl -ROfk --output-dir $temp_dir $firmware_url; then
			mv $temp_dir/${firmware_url##*/} ./ && ls -l ${firmware_url##*/}
		else
			print_w "Not found $firmware_url"
		fi
	fi

	if [ -f ${bootimg_url##*/} ]; then
		echo -e "${bootimg_url##*/} already exists"
	else
		echo -e "\n Downloading $bootimg_url "
		if curl -ROfk --output-dir $temp_dir $bootimg_url; then
			mv $temp_dir/${bootimg_url##*/} ./
		else
			print_e "Failed to download boot image" && exit
		fi
	fi

	if [ -f ${rootfsimg_url##*/} ]; then
		echo -e "${rootfsimg_url##*/} already exists"
	else
		echo -e "\n Downloading $rootfsimg_url "
		if curl -ROfk --output-dir $temp_dir $rootfsimg_url; then
			mv $temp_dir/${rootfsimg_url##*/} ./
		else
			print_e "Failed to download rootfs image" && exit
		fi
	fi

	print_n "Downloaded distro images [Done]"
}

check_board_valid() {
	if [ -z "$1" ] || [ "$1" = "all" ]; then
		echo -e "Error: Please specify the board, for example: -m imx8mpevk \n"
		exit 1
	fi
    if [[ " $ls_machine_list " =~ " $1 " ]] || [[ " $imx_machine_list " =~ " $1 " ]]; then
        return 0
    else
        echo "Error: Invalid board: '$1'."
        echo "Valid machine name:"
        echo "LS_MACHINE_LIST: $ls_machine_list"
        echo "IMX_MACHINE_LIST: $imx_machine_list"
        exit 1
    fi
}

check_required_cmd() {
    local missing_deps=()
    for cmd in parted curl sudo fuser mount mkfs.ext4 zstd udevadm partprobe; do
        if ! command -v "$cmd" &>/dev/null; then
            missing_deps+=("$cmd")
        fi
    done
    if [ ${#missing_deps[@]} -gt 0 ]; then
        print_e "Missing required commands: ${missing_deps[*]}"
        print_e "Please install them first"
        exit 1
    fi
}

print_e() {
    echo -e "${RED}$1 ${NC}"
}

print_n() {
    echo -e "${green}$1 ${NC}"
}

print_w() {
    echo -e "${YELLOW}$1 ${NC}"
}

print_d() {
    echo -e "${GREEN}$1     [Done] ${NC}"
}

RED='\e[1;31m'
GREEN='\e[1;32m'
green='\e[0;32m'
YELLOW='\e[1;33m'
NC='\e[0m'

[ -z "$1" -o "$1" = "-h" -o "$1" = "--help" ] && usage && exit

ARGS=$(getopt -a -o m:f:b:B:r:R:u:p:d:s:i:e:o:hvF \
       -l machine:,firmware:,bootimg:,bootpart:,rootfsimg:,rootpart:,partition:,url:,device:,efi:,startblock:,instruction:,offset:,help,version,force -- "$@")

[ $? -ne 0 ] && usage
eval set -- "${ARGS}"
while true
do
	case "$1" in
	-m|--machine)
		machine=$2; check_board_valid $machine; shift;;
	-f|--firmware)
		firmware=$2; shift;;
	-s|--startblock)
		startblock=$2; shift;;
	-b|--bootimg)
		bootimg=$2; shift;;
	-B|--bootpart)
		bootpartnum=$2; shift;;
	-r|--rootfsimg)
		rootfsimg=$2; shift;;
	-R|--rootpart)
		rootpartnum=$2; shift;;
	-p|--partition)
		diskpartlist=$2; shift;;
	-u|--url)
		url=$2; shift;;
	-d|--device)
		mediadevice=$2; shift;;
	-i|instruction)
		if [ ${2:0:5} = auto: ]; then
		    distrover=$(echo $2 | cut -d: -f2)
		    echo distroversion: $distrover
		elif [ ${2:0:9} = download: ]; then
		    distrover=$(echo $2 | cut -d: -f2)
		elif [ ${2:0:7} = backup: ]; then
		    backupdir=$(echo $2 | cut -d: -f2)
		fi
		instruction=$(echo $2 | cut -d: -f1)
		shift;;
	-o|--offset)
		disk_offset=$2; shift;;
	-v|--version)
		echo flex-installer version: $FIVERSION; exit;;
	-h|--help)
		usage;;
	-F|--force)
		force_opt=y;;
	--)
		shift; break;;
	esac
shift
done

mntdir=$(mktemp -d /tmp/flex-installer.XXXXXX)
if [ $? -ne 0 ] || [ -z "$mntdir" ]; then
    print_e "Failed to create temporary mount directory"
    exit 1
fi
sudo chmod 755 "$mntdir"

if [ -n "$instruction" ] && [ $instruction != auto -a $instruction != pf -a $instruction != download \
     -a $instruction != install -a $instruction != list -a $instruction != backup -a $instruction != mkwic ]; then
    print_e "Invalid instruction $instruction, valid: auto, pf, download, install, list, backup"; exit 1
fi

if [ "$instruction" = list ]; then
    print_n "\nSupported machine list:"
    print_n "  imx machine: $imx_machine_list"
	print_n "  layerscape machine: $ls_machine_list"
    print_n "\nSupported environment of installation:"
    print_n "  Linux host PC, ARM board running LSDK distro, ARM board running TinyLinux"
	exit 0
fi

[ -z "$instruction" ] && instruction=install

if [ -z "$mediadevice" ] && [ $instruction = install -o $instruction = auto -o $instruction = pf ]; then
    print_e "Please specify '-d <device>'"; exit 1
fi

[ -f /etc/issue ] && [[ `cat /etc/issue | grep NXP | grep tiny` ]] && intinyrfs=y || intinyrfs=n

if [ $instruction = mkwic ]; then
    if [ -n "$mediadevice" ]; then
        print_w "NOTICE: '-d $mediadevice' option is ignored for mkwic instruction"
        print_w "mkwic will automatically use an available loop device"
    fi
	mediadevice=`sudo losetup -f`
fi

if [ $intinyrfs = y -a $instruction != download ]; then
    get_device_name_in_tinydistro
elif [ $intinyrfs = n -a $instruction != download ]; then
    [ ! -b $mediadevice ] && print_e "$mediadevice does not exist on this host machine" && exit 1
    get_device_name_on_host
fi

if [ $instruction = auto -o $instruction = pf -o $instruction = install ]; then
    disksize=$[ `sudo fdisk -ls /dev/$devname` / 1000000 ]
    print_n "/dev/$devname: $disksize GB"
fi

[ -z "$disksize" ] && disksize=0
[ -n "$distrover" ] && distroversion=$distrover || distroversion=${FIVERSION}
linux_ver=$(get_linux_version "$distroversion")

if [ -z "$diskpartlist" ]; then
    [ "${devname:0:4}" = loop -o $disksize -le 16 ] && diskpartition=$DEFAULT_LOOP_DEVICE_PARTITION || \
    diskpartition=$DEFAULT_DISK_PARTITION
    [ $instruction = auto -o $instruction = pf ] && [ $disksize -le 16 ] && \
    print_w "The capacity of /dev/$devname is only $disksize GB, using partitions: $DEFAULT_LOOP_DEVICE_PARTITION"
else
   diskpartition=$diskpartlist
fi

[ -z "$pnum" ] && pnum=$DEFAULT_PARTITION_NUMBER
if [ -z "$bootpartnum" ]; then
    bootpartnum=$DEFAULT_BOOT_PARTITION_NUM
fi

check_partition_number
[ -z "$bootpartnum" ] && bootpartnum=$DEFAULT_BOOT_PARTITION_NUM
[ -z "$rootpartnum" ] && rootpartnum=$DEFAULT_ROOT_PARTITION_NUM
backuppartnum=$pnum

bootdev=/dev/${devpartname}$bootpartnum
rootdev=/dev/${devpartname}$rootpartnum
backupdev=/dev/${devpartname}$backuppartnum
bootpartition=$mntdir/${devpartname}${bootpartnum}
rootpartition=$mntdir/${devpartname}${rootpartnum}
backuppartition=$mntdir/${devpartname}${backuppartnum}

if [ $instruction = pf ]; then
    partition_format_disk $diskpartition
    umount_device
	sudo partprobe /dev/$devname 2>/dev/null || true
	sudo udevadm settle
	sync
	exit 0
elif [ $instruction != download ] && [ $instruction != mkwic ]; then
    check_device_partitions
fi

if [ $instruction != backup ]; then
	check_board_valid $machine
	if echo $machine | grep -q imx; then
		portfolio=IMX
	else
		portfolio=LS
	fi
fi

[ -f $rootpartition ] && [ "`ls -A $rootpartition`" != "" ] && print_e "Directory $mntdir is not empty, please clean it first" && exit

if [ $instruction != download ] && [ $instruction != mkwic ]; then
    sudo mkdir -p $bootpartition $rootpartition $backuppartition
fi

[ -n "$bootimg" ] && bootimg_n=$bootimg || bootimg_n=boot_${portfolio}_arm64_lts_${linux_ver}.tar.zst
[ -n "$rootfsimg" ] && rootfsimg_n=$rootfsimg || rootfsimg_n=rootfs_${distroversion}_debian_base_arm64.tar.zst
if [ -n "$firmware" ]; then
	firmware_n=$firmware
else
	if [[ $distroversion == lsdk24* || $distroversion == lsdk25* ]] || [[ " ${ls_machine_list} " =~ ${machine} ]]; then
		firmware_n=firmware_"${machine}"_sdboot.img
	else
		firmware_n="${machine}"-sd-flash.bin
	fi
fi

if [ -z "$url" -a -z "$distrover" ]; then
    url=$DEFAULT_DISTRO_SVR_URL
elif [ -z "$url" -a -n "$distrover" ]; then
    url=${DEFAULT_DISTRO_SVR_URL%/*}/$distrover
fi

bootimg_url=$url/$bootimg_n
rootfsimg_url=$url/$rootfsimg_n
firmware_url=$url/$firmware_n

check_required_cmd

if [ $instruction = auto ]; then
    check_network_access
    [ $intinyrfs = y ] && cd $rootpartition
    download_distro
    check_images_format
    [ -z "$machine" ] && { print_e "Please specify '-m <machine>' for installation"; exit 1; }
    flex_install_distro
elif [ $instruction = download ]; then
    check_network_access
    download_distro
elif [ $instruction = install ]; then
    # Check at least one image file is provided and exists
    has_valid_image=0

    if [ -n "$rootfsimg" ]; then
        [ ! -e "$rootfsimg" ] && print_e "Rootfs image not found: $rootfsimg" && exit 1
        has_valid_image=1
    fi

    if [ -n "$bootimg" ]; then
        [ ! -e "$bootimg" ] && print_e "Boot image not found: $bootimg" && exit 1
        has_valid_image=1
    fi

    if [ -n "$firmware" ]; then
        [ ! -e "$firmware" ] && print_e "Firmware image not found: $firmware" && exit 1
        has_valid_image=1
    fi

    # Ensure at least one image is provided
    [ $has_valid_image -eq 0 ] && print_e "At least one image (rootfs/boot/firmware) must be provided" && exit 1
    [ -z "$machine" ] && print_e "Please specify '-m <machine>' for mkwic" && exit 1
    check_images_format

    flex_install_distro
elif [ $instruction = mkwic ]; then
    # Clean mounted devices
    if mount | grep $mntdir/$devname; then
        sudo umount $mntdir/$devname* 1>/dev/null 2>&1 || true
    fi
    # Check required image files
    [ -z "$rootfsimg" -o ! -e "$rootfsimg" ] && print_e "Not found rootfs image" && exit 1
    [ -z "$bootimg" -o ! -e "$bootimg" ] && print_e "Not found boot image" && exit 1
    [ -z "$firmware" -o ! -e "$firmware" ] && print_e "Not found firmware image" && exit 1
    [ -z "$machine" ] && print_e "Please specify '-m <machine>' for mkwic" && exit 1
    # Check and set partition configuration first
    if [ -n "$diskpartlist" ]; then
        diskpartition=$diskpartlist
        check_partition_number
    else
        # Use default loop device partition configuration
        diskpartition=$DEFAULT_LOOP_DEVICE_PARTITION
        pnum=$(echo $diskpartition | cut -d= -f1 | sed 's/P//')
        check_partition_number
    fi

    # Validate partition size against image size limit
    total_size_mb=$(calculate_partition_total_size "$diskpartition")
    if [ $? -ne 0 ]; then
        exit 1
    fi

    if [ $total_size_mb -gt $DEFAULT_SDCARD_IMG_SIZE_MB ]; then
        print_e "ERROR: Total partition size (${total_size_mb}MB) exceeds WIC image size limit (${DEFAULT_SDCARD_IMG_SIZE_MB}MB)"
        print_e "Partition config: $diskpartition"
        print_e "Please reduce partition sizes or increase DEFAULT_SDCARD_IMG_SIZE_MB"
        exit 1
    fi

    # Define WIC image filename
    wic_image="rootfs_${distroversion}_debian_${machine}.wic"
    wic_image_zst="${wic_image}.zst"

    print_n "Creating ${wic_image} with size ${DEFAULT_SDCARD_IMG_SIZE_MB}MB, waiting"
    # Create WIC image file
    rm -f ${wic_image}
    dd if=/dev/zero of=${wic_image} bs=1M count=$DEFAULT_SDCARD_IMG_SIZE_MB
    # Clean up existing loop devices
    loopdev=$(sudo losetup -j ${wic_image} | cut -d' ' -f1)
    if [ -n "$loopdev" ]; then
        for lpn in $loopdev; do
            sudo losetup -d ${lpn::-1}
        done
    fi
    # Setup loop device
    sudo losetup /dev/$devname ${wic_image}
    # Check image format
    check_images_format

    # Partition and format disk
    partition_format_disk $diskpartition

	rootpartnum=$DEFAULT_ROOT_PARTITION_NUM
	backuppartnum=$pnum
    # Update partition device paths
    bootdev=/dev/${devpartname}$bootpartnum
    rootdev=/dev/${devpartname}$rootpartnum
    backupdev=/dev/${devpartname}$backuppartnum
    bootpartition=$mntdir/${devpartname}${bootpartnum}
    rootpartition=$mntdir/${devpartname}${rootpartnum}
    backuppartition=$mntdir/${devpartname}${backuppartnum}
    # Call installation function directly
    flex_install_distro
    # Clean up loop device
    sudo losetup -d /dev/$devname
    # Display result
    fdisk -l ${wic_image}

    # Compress WIC image with zstd
    print_n "Compressing ${wic_image} to ${wic_image_zst}"
    pzstd -f ${wic_image} -o ${wic_image_zst}
    rm -f ${wic_image}

    print_n "Created ${wic_image_zst} successfully\n"
    # ls -lh ${wic_image_zst}
    print_n "Run the following command to burn ${wic_image_zst} to SD card:"
    print_n "zstd -d ${wic_image_zst} && sudo dd if=${wic_image} of=/dev/<dev> bs=1M conv=fsync status=progress\n"
elif [ $instruction = backup ]; then
    mount_device
    [ -z "$backupdir" ] && backupdir=$backuppartition; mkdir -p $backupdir; timestamp=$(date +%Y%m%d%H%M)
    print_n "Backup $backupdir/backup_rootfs_$timestamp.tar.zst"

    (cd $rootpartition && sudo tar --zstd -cf $backupdir/backup_rootfs_$timestamp.tar.zst *)

    du -sh $backupdir/backup*.tar.zst
    print_n "Backup completed successfully"
    umount_device
fi
