# [general]
machine=imx8qmmek
kconfig_soc=SOC_IMX8QMMEK

ATF_PLATFORM="imx8qm"
UBOOT_CONFIG="imx8qm_mek_defconfig"

# offset 32k for imx8qm B0, 33k for imx8qm A0
DISK_BOOTLOADER_OFFSET="32768"

COMPOSITE_IMG1_FILE_sd="images/${machine}-sd-flash.bin"
